config/routes.rb
Rails.application.routes.draw do

  devise_for :administrators, controllers: { sessions: "administrators/sessions" }

  devise_for :judges

  root 'players#index'

  resources :players

  resources :grades, only: [:new, :create, :show, :destroy]

  namespace :admin do
    root 'administrators#index'
    concern :gradetable do
      resources :grades
    end
    resources :judges, concerns: :gradetable
    resources :players, concerns: :gradetable
    resources :administrators
  end

end

app/models/administrator.rb
# == Schema Information
#
# Table name: administrators
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Administrator < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :login

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    where(conditions).where(["email = :value", { :value => login.strip }]).first
  end
end

app/controllers/admin/administrators_controller.rb
module Admin
  class AdministratorsController < Admin::BaseController
    before_action :set_administrator, only: [:show, :edit, :update, :destroy]
    respond_to :html, :js
    def index
      @administrators = Administrator.all
    end

    def show
    end

    def new
      @administrator = Administrator.new
    end

    def create
      @administrator = Administrator.new(administrator_params)
      if @administrator.save
        flash[:notice] = "评委创建成功"
        respond_with @administrators
      else
        flash[:error] = "创建失败"
        render :new
      end
    end

    def edit
      respond_with @administrator
    end

    def update
      if @administrator.update(administrator_params)
        flash[:notice] = "更新成功"
        respond_with @administrators
      else
        flash[:error] = "更新失败"
      end
    end

    def destroy
      @administrator.destroy
      redirect_to admin_administrators_path
    end

    private
      def set_administrator
        @administrator = Administrator.find(params[:id])
      end

      def administrator_params
        params.require(:administrator).permit(:email, :password ,:password_confirmation)
      end
  end
end

app/controllers/administrators/sessions_controller.rb
module Admin
  class Administrators::SessionsController < Devise::SessionsController
    layout 'admin'
  # before_filter :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    def new
      super
    end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.for(:sign_in) << :attribute
    # end
  end
end

app/views/admin/administrators/_administrators_modal.html.erb
<div id="administratorModal" class="modal fade rooms-modal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title"><span class="text-primary"><%#= administrator.email %></span>添加管理员信息</h3>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-lg-12">
            <%= form_for [:admin, administrator], remote: true, format: :js do |f| %>
            <div class="form-group">
              <div class="input-group input-padding" style="width: 100%;">
                <%= f.text_field :email, class: 'form-control', placeholder: '邮箱'%>
              </div>
              <% if administrator.errors[:email].any? %>
                <dd class="error text-danger"><%= administrator.errors[:email][0] %></dd>
              <% end %>
            </div>
            <div class="form-group">
              <div class="input-group input-padding" style="width: 100%;">
                <%= f.text_field :password, class: 'form-control txt', placeholder: '密码'%>
              </div>
              <% if administrator.errors[:password].any? %>
                <dd class="error text-danger"><%= administrator.errors[:password][0] %></dd>
              <% end %>
            </div>
            <div class="form-group">
              <div class="input-group input-padding" style="width: 100%;">
                <%= f.text_field :password_confirmation, class: 'form-control txt', placeholder: '确认密码'%>
              </div>
              <% if administrator.errors[:password_confirmation].any? %>
                <dd class="error text-danger"><%= administrator.errors[:password_confirmation][0] %></dd>
              <% end %>
            </div>
            <div class="text-center">
              <%= f.submit "提交", class: "btn sub-btn btn-primary", data: { disable_with: '正在提交...' } %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/administrators/create.js.erb
<% if @administrator.errors.present? %>
  $(".modal-backdrop").remove();
  $("#administratorModalContent").html("<%= escape_javascript( render "administrators_modal", administrator: @administrator )%>");
  $('#administratorModal').modal('show');
<% else %>
  location.href = "<%= admin_administrators_path %>"
<% end  %>

app/views/admin/administrators/edit.js.erb
$("#administratorModalContent").html("<%= escape_javascript( render "administrators_modal", administrator: @administrator )%>");
$('#administratorModal').modal('show')
$(".modal-header").click();

app/views/admin/administrators/index.html.erb
<div id="wrapper">
  <%= render 'admin/share/left_nav'%>
  <div id="page-wrapper" class="gray-bg">
    <%= render 'admin/share/header'%>
    <div class="wrapper wrapper-content">
      <div class="lg-box animated fadeInRightBig">
        <div class="row">
          <div class="col-lg-12">
            <div class="ibox float-e-margins">
              <div class="ibox-title">
                <h5>管理员信息表</h5>
                <div class="pull-right">
                  <%= link_to new_admin_administrator_path, remote: true, format: :js, class: "ibox-title-new member-new" do %>
                    <i class="fa fa-plus fa-lg"></i>添加管理员
                  <% end %>
                </div>
              </div>
              <div class="ibox-content">
                <table class="table">
                  <thead>
                    <tr class="text-center">
                      <th>排序</th>
                      <th>邮箱</th>
                      <th>编辑</th>
                    </tr>
                  </thead>
                  <tbody>
                  <% @administrators.each_with_index do |administrator, index| %>
                    <tr>
                      <td><%= index + 1 %></td>
                      <td><%= administrator.email %></td>
                      <td>
                        <%= link_to edit_admin_administrator_path(id: administrator.id), class: 'btn btn-xs btn-default', remote: true, format: :js do %>
                          <span class="glyphicon glyphicon-edit"></span>
                        <% end %>
                        <%= link_to admin_administrator_path(id: administrator.id), method: :delete, class: 'btn btn-xs btn-danger' do %>
                          <span class="glyphicon glyphicon-trash"></span>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                  </tbody>
                  <tfoot>
                    <tr>
                      <td class="text-center" colspan="6">
                        <ul class="pagination"></ul>
                      </td>
                    </tr>
                  </tfoot>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <%= render 'admin/share/footer'%>
  </div>
</div>
<div id="administratorModalContent"></div>

app/views/admin/administrators/new.js.erb
$(".modal-backdrop").remove();
$("#administratorModalContent").html("<%= escape_javascript( render "administrators_modal", administrator: @administrator  )%>");
$('#administratorModal').modal('show');

app/views/admin/administrators/update.js.erb
<% if @administrator.errors.present? %>
  $(".modal-backdrop").remove();
  $("#administratorModalContent").html("<%= escape_javascript( render "administrators_modal", administrator: @administrator )%>");
  $('#administratorModal').modal('show');
<% else %>
  location.href = "<%= admin_administrators_path %>"
<% end  %>