config/routes.rb
Rails.application.routes.draw do

  devise_for :administrators, controllers: { sessions: "administrators/sessions" }

  devise_for :judges

  root 'players#index'

  resources :players

  resources :grades, only: [:new, :create, :show, :destroy]

  namespace :admin do
    root 'administrators#index'
    concern :gradetable do
      resources :grades
    end
    resources :judges, concerns: :gradetable
    resources :players, concerns: :gradetable
    resources :administrators
  end

end

app/models/player.rb
# == Schema Information
#
# Table name: players
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  title      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  number     :string(255)
#  college    :string(255)
#  phone      :string(255)
#

class Player < ActiveRecord::Base
  has_many :grades, :dependent => :destroy
  has_many :judges, through: :grades
  validates_presence_of :name, :number, :title, :message => "必须填写!"
  validates_uniqueness_of :number,:case_sensitive => false, :message => "编号已存在!"
end

app/controllers/admin/players_controller.rb
module Admin
  class PlayersController < Admin::BaseController
    before_action :set_player, only: [:show, :edit, :update, :destroy]
    respond_to :html, :js
    def index
      @players = Player.all
      respond_to do |format|
          format.xls {
              send_data( xls_content_for(@players),
                  :type => "text/excel;charset=utf-8; header=present",
                  :filename => "2015上海市高等职业院校教师教学信息化说课比赛成绩表.xls" )
          }
          format.html
      end
    end

    def show
      @player = Player.find(params[:id])
      @grades = @player.grades
    end

    def new
      @player = Player.new
    end

    def create
      @player = Player.new(player_params)
      if @player.save
        flash[:notice] = "评委创建成功"
        respond_with @players
      else
        flash[:error] = "创建失败"
        render :new
      end
    end

    def edit
      respond_with @player
    end

    def update
      if @player.update(player_params)
        flash[:notice] = "更新成功"
        respond_with @players
      else
        flash[:error] = "更新失败"
      end
    end

    def destroy
      @player.destroy
      redirect_to admin_players_path
    end

    private
    def set_player
      @player = Player.find(params[:id])
    end

    def player_params
      params.require(:player).permit(:number, :name, :title, :college, :phone)
    end

    def xls_content_for(objs)
      xls_report = StringIO.new
      book = Spreadsheet::Workbook.new
      sheet1 = book.create_worksheet :name => "成绩统计"

      blue = Spreadsheet::Format.new :color => :blue, :weight => :bold, :size => 10
      sheet1.row(0).default_format = blue

      sheet1.row(0).concat %w{序号 姓名 院校 说课名称 联系方式 最高分 最低分 平均分 参评人数}
      count_row = 1
          objs.each do |obj|
          sheet1[count_row, 0] = obj.number
          sheet1[count_row, 1] = obj.name
          sheet1[count_row, 2] = obj.college
          sheet1[count_row, 3] = obj.title
          sheet1[count_row, 4] = obj.phone
          sheet1[count_row, 5] = obj.grades.maximum(:total)
          sheet1[count_row, 6] = obj.grades.minimum(:total)
          sheet1[count_row, 7] = (obj.grades.sum(:total).to_f / obj.grades.count).round(1)
          sheet1[count_row, 8] = obj.grades.count
          count_row += 1
      end

      book.write xls_report
      xls_report.string
    end
  end
end

app/controllers/players_controller.rb
class PlayersController < BaseController
	respond_to :html, :js

	def index
		@players = Player.all
	end

	def show
		@player = Player.find(params[:id])
		respond_with @player
	end
end

app/helpers/players_helper.rb
module PlayersHelper
	def is_judged(player, current_judge)
		Grade.where(player_id: player.id, judge_id: current_judge.id).present?
	end
end

app/views/admin/players/_players_modal.html.erb
<div id="playerModal" class="modal fade rooms-modal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title"><span class="text-primary"><%#= player.name %></span>添加参赛者信息</h3>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-lg-12">
            <%= form_for [:admin, player], remote: true, format: :js do |f| %>
            <div class="form-group">
              <div class="input-group input-padding" style="width: 100%;">
                <%= f.text_field :number, class: 'form-control', placeholder: '编号'%>
              </div>
              <% if player.errors[:number].any? %>
                <dd class="error text-danger"><%= player.errors[:number][0] %></dd>
              <% end %>
            </div>
            <div class="form-group">
              <div class="input-group input-padding" style="width: 100%;">
                <%= f.text_field :name, class: 'form-control', placeholder: '姓名'%>
              </div>
              <% if player.errors[:name].any? %>
                <dd class="error text-danger"><%= player.errors[:name][0] %></dd>
              <% end %>
            </div>
             <div class="form-group">
              <div class="input-group input-padding" style="width: 100%;">
                <%= f.text_field :college, class: 'form-control', placeholder: '院校'%>
              </div>
              <% if player.errors[:college].any? %>
                <dd class="error text-danger"><%= player.errors[:college][0] %></dd>
              <% end %>
            </div>
            <div class="form-group">
              <div class="input-group input-padding" style="width: 100%;">
                <%= f.text_field :title, class: 'form-control', placeholder: '说课名称'%>
              </div>
              <% if player.errors[:title].any? %>
                <dd class="error text-danger"><%= player.errors[:title][0] %></dd>
              <% end %>
            </div>
            <div class="form-group">
              <div class="input-group input-padding" style="width: 100%;">
                <%= f.text_field :phone, class: 'form-control', placeholder: '联系电话'%>
              </div>
              <% if player.errors[:phone].any? %>
                <dd class="error text-danger"><%= player.errors[:phone][0] %></dd>
              <% end %>
            </div>
            <div class="text-center">
              <%= f.submit "提交", class: "btn sub-btn btn-primary", data: { disable_with: '正在提交...' } %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/players/_players_show_modal.html.erb
<div id="playerModal" class="modal fade rooms-modal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title"><span class="text-primary"><%#= player.name %></span>得分详情</h3>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-lg-12">
            <table class="table">
                  <thead>
                    <tr class="text-center">
                      <th>序号</th>
                      <th>评委</th>
                      <th>定位目标</th>
                      <th>课程内容</th>
                      <th>教学设计</th>
                      <th>表达与教态</th>
                      <th>总分</th>
                    </tr>
                  </thead>
                  <tbody>
                  <% @grades.each_with_index do |grade, index| %>
                    <tr>
                      <td><%= index + 1 %></td>
                      <td><%= grade.judge.name %></td>
                      <td>
                        
                          <%= grade.target %>分
                      
                      </td>
                      <td>
                        
                          <%= grade.content %>分
                      
                      </td>
                      <td>
                    
                          <%= grade.plan %>分
                   
                      </td>
                      <td>
                       
                          <%= grade.express %>分
                     
                      </td>
                      <td>
                          <%= grade.target+grade.content+grade.plan+grade.express %>分
                     
                      </td>
                      
                    </tr>
                  <% end %>
                  </tbody>
                  <tfoot>
                    <tr>
                      <td class="text-center" colspan="6">
                        <ul class="pagination"></ul>
                      </td>
                    </tr>
                  </tfoot>
                </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/players/create.js.erb
<% if @player.errors.present? %>
  $(".modal-backdrop").remove();
  $("#playerModalContent").html("<%= escape_javascript( render "players_modal", player: @player )%>");
  $('#playerModal').modal('show');
<% else %>
	$('#playerModal').modal('hide');
  location.href = "<%= admin_players_path %>";
<% end  %>

app/views/admin/players/edit.js.erb
$("#playerModalContent").html("<%= escape_javascript( render "players_modal", player: @player )%>");
$('#playerModal').modal('show')
$(".modal-header").click();

app/views/admin/players/index.html.erb
<div id="wrapper">
  <%= render 'admin/share/left_nav'%>
  <div id="page-wrapper" class="gray-bg">
    <%= render 'admin/share/header'%>
    <div class="wrapper wrapper-content">
      <div class="lg-box animated fadeInRightBig">
        <div class="row">
          <div class="col-lg-12">
            <div class="ibox float-e-margins">
              <div class="ibox-title">
                <h5>参赛选手信息表</h5>
                <div class="pull-right">
                  <%= link_to new_admin_player_path, remote: true, format: :js, class: "ibox-title-new member-new" do %>
                    <i class="fa fa-plus fa-lg"></i>添加参赛者
                  <% end %>
                </div>
              </div>
              <div class="ibox-content">
                <table class="table">
                  <thead>
                    <tr class="text-center">
                      <th>序号</th>
                      <th>姓名</th>
                      <th>院校</th>
                      <th>说课名称</th>
                      <th>联系方式</th>
                      <th>最高分</th>
                      <th>最低分</th>
                      <th>平均分</th>
                      <th>参评人数</th>
                      <th>编辑</th>
                    </tr>
                  </thead>
                  <tbody>
                  <% @players.each_with_index do |player, index| %>
                    <tr>
                      <td><%= player.number %></td>
                      <td><%= player.name %></td>
                      <td><%= player.college %></td>
                      <td><%= player.title %></td>
                      <td><%= player.phone %></td>
                      <td>
                        <% if player.grades.any? %>
                          <%= player.grades.maximum(:total) %>分
                        <% else %>
                          0分
                        <% end %>  
                      </td>
                      <td>
                        <% if player.grades.any? %>
                          <%= player.grades.minimum(:total) %>分
                        <% else %>
                          0分
                        <% end %> 
                      </td>
                      <td>
                        <% if player.grades.any? %>
                          <%= (player.grades.sum(:total).to_f / player.grades.count).round(1)%>分
                        <% else %>
                          0分
                        <% end %> 
                      </td>
                      <td>
                        <% if player.grades.any? %>
                          <%= player.grades.count %>人
                        <% else %>
                          0人
                        <% end %> 
                      </td>
                      <td>
                        <%= link_to admin_player_path(id: player.id), class: 'btn btn-xs btn-info', remote: true, format: :js do %>
                          <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
                        <% end %>
                        <%= link_to edit_admin_player_path(id: player.id), class: 'btn btn-xs btn-default', remote: true, format: :js do %>
                          <span class="glyphicon glyphicon-edit"></span>
                        <% end %>
                        <%= link_to admin_player_path(id: player.id), method: :delete, class: 'btn btn-xs btn-danger' do %>
                          <span class="glyphicon glyphicon-trash"></span>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                  </tbody>
                  <tfoot>
                    <tr>
                      <td class="text-center" colspan="6">
                        <ul class="pagination"></ul>
                      </td>
                    </tr>
                  </tfoot>
                </table>
                <%= link_to("导出为Excel", admin_players_path(format: 'xls'), class: "btn btn-success") %>
                <%#= link_to("清空所有分数", grade_path, method: :delete, class: "btn btn-danger") %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <%= render 'admin/share/footer'%>
  </div>
</div>
<div id="playerModalContent"></div>

app/views/admin/players/new.js.erb
$(".modal-backdrop").remove();
$("#playerModalContent").html("<%= escape_javascript( render "players_modal", player: @player  )%>");
$('#playerModal').modal('show');

app/views/admin/players/show.js.erb
$(".modal-backdrop").remove();
$("#playerModalContent").html("<%= escape_javascript( render "players_show_modal",locals:{grades: @grades})%>");
$('#playerModal').modal('show');

app/views/admin/players/update.js.erb
<% if @player.errors.present? %>
  $(".modal-backdrop").remove();
  $("#playerModalContent").html("<%= escape_javascript( render "players_modal", player: @player )%>");
  $('#playerModal').modal('show');
<% else %>
  location.href = "<%= admin_players_path %>"
<% end  %>