config/routes.rb
Rails.application.routes.draw do

  devise_for :administrators, controllers: { sessions: "administrators/sessions" }

  devise_for :judges

  root 'players#index'

  resources :players

  resources :grades, only: [:new, :create, :show, :destroy]

  namespace :admin do
    root 'administrators#index'
    concern :gradetable do
      resources :grades
    end
    resources :judges, concerns: :gradetable
    resources :players, concerns: :gradetable
    resources :administrators
  end

end

app/views/admin/share/_footer.html.erb
<div class="footer">
  <div>
    <strong>Copyright</strong> 大唐邦彦（上海）信息技术有限公司 &copy; 11－11－2015
  </div>
</div>

app/views/admin/share/_header.html.erb
<div class="row border-bottom">
  <nav class="navbar navbar-static-top  " role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
      <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
    </div>
    <ul class="nav navbar-top-links navbar-right">
      <li>
        <% if current_administrator %>
          <%= link_to destroy_administrator_session_path, :method => :delete do |i| %>
            <i class="fa fa-sign-out"></i>退出
          <% end %>
        <% else %>
          <%= link_to new_administrator_session_path, :method => :delete do |i| %>
            <i class="fa fa-sign-out"></i>登录
          <% end %>
        <% end %>
      </li>
    </ul>
  </nav>
</div>
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-sm-8">
    <h2>2015上海市高等职业院校教师教学信息化说课比赛</h2>
    <ol class="breadcrumb">
      <li>
        <a>This is</a>
      </li>
      <li class="active">
        <strong>
          <% if params[:controller] == "admin/players" %>
            参赛选手信息
          <% end %>
          <% if params[:controller] == "admin/judges" %>
            评委信息
          <% end %> 
          <% if params[:controller] == "admin/administrators" %>
            管理员信息   
          <% end %>  
        </strong>
      </li>
    </ol>
  </div>
</div>

app/views/admin/share/_left_nav.html.erb
<nav class="navbar-default navbar-static-side" role="navigation">
  <div class="sidebar-collapse">
    <ul class="nav metismenu" id="side-menu">
      <li class="<%= "active" if params[:controller] == "admin/judges" %>">
      <%= link_to admin_judges_path do |i| %>
        <i class="fa fa-th-large"></i> <span class="nav-label">评委信息</span>
      <% end %>  
      </li>
      <li class="<%= "active" if params[:controller] == "admin/players" %>">
        <%= link_to admin_players_path do |i| %>
          <i class="fa fa-diamond"></i> <span class="nav-label">参赛选手信息</span>
        <% end %>
      </li>
      <li class="<%= "active" if params[:controller] == "admin/administrators" %>">
      <%= link_to admin_administrators_path do |i| %>
        <i class="fa fa-bar-chart-o"></i> <span class="nav-label">管理员信息</span>
      <% end %>
      </li>
    </ul>
  </div>
</nav>