config/routes.rb
Rails.application.routes.draw do

  devise_for :administrators, controllers: { sessions: "administrators/sessions" }

  devise_for :judges

  root 'players#index'

  resources :players

  resources :grades, only: [:new, :create, :show, :destroy]

  namespace :admin do
    root 'administrators#index'
    concern :gradetable do
      resources :grades
    end
    resources :judges, concerns: :gradetable
    resources :players, concerns: :gradetable
    resources :administrators
  end

end

app/models/judge.rb
# == Schema Information
#
# Table name: judges
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  phone                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string(255)
#

class Judge < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :grades, :dependent => :destroy
  has_many :players, through: :grades

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         

  attr_accessor :login

 	# 使用手机号登录
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    where(conditions).where(["name = :value", { :value => login.strip }]).first
	end

	#判断是否需要更新密码
	# def update_judge(params)
	# 	if params[:password].present? || params[:password_confirmation].present?
	# 		update(params)
	# 	else
	# 		update_without_password(params)
	# 	end
	# end

	# 不验证邮箱
	def email_required?
		false
	end

end

app/controllers/admin/judges_controller.rb
module Admin
  class JudgesController < Admin::BaseController
    before_action :set_judge, only: [:show, :edit, :update, :destroy]
    respond_to :html, :js
    def index
      @judges = Judge.all
    end

    def show
      respond_with Judge.find(params[:id])
    end

    def new
      @judge = Judge.new
    end

    def create
      @judge = Judge.new(judge_params)
      if @judge.save
        flash[:notice] = "评委创建成功"
        respond_with @judges
      else
        flash[:error] = "创建失败"
        render :new
      end
    end

    def edit
      respond_with @judge
    end

    def update
      if @judge.update(judge_params)
        flash[:notice] = "更新成功"
        respond_with @judges
      else
        flash[:error] = "更新失败"
      end
    end

    def destroy
      @judge.destroy
      redirect_to admin_judges_path
    end

    private
      def set_judge
        @judge = Judge.find(params[:id])
      end

      def judge_params
        params.require(:judge).permit(:name, :phone, :email, :password ,:password_confirmation)
      end
  end
end

app/views/admin/judges/_judges_modal.html.erb
<div id="judgeModal" class="modal fade rooms-modal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title"><span class="text-primary"><%#= judge.name %></span>添加评委信息</h3>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-lg-12">
            <%= form_for [:admin, judge], remote: true, format: :js do |f| %>
            <div class="form-group">
              <div class="input-group input-padding" style="width: 100%;">
                <%= f.text_field :name, class: 'form-control', placeholder: '姓名'%>
              </div>
              <% if judge.errors[:name].any? %>
                <dd class="error text-danger"><%= judge.errors[:name][0] %></dd>
              <% end %>
            </div>
            <div class="form-group">
              <div class="input-group input-padding" style="width: 100%;">
                <%= f.text_field :email, class: 'form-control', placeholder: '邮箱'%>
              </div>
              <% if judge.errors[:email].any? %>
                <dd class="error text-danger"><%= judge.errors[:email][0] %></dd>
              <% end %>
            </div>
            <div class="form-group">
              <div class="input-group input-padding" style="width: 100%;">
                <%= f.text_field :phone, class: 'form-control', onkeyup:"KeyP(this);", placeholder: '手机'%>
              </div>
              <% if judge.errors[:phone].any? %>
                <dd class="error text-danger"><%= judge.errors[:phone][0] %></dd>
              <% end %>
            </div>
            <div class="form-group">
              <div class="input-group input-padding" style="width: 100%;">
                <%= f.text_field :password, class: 'form-control txt', placeholder: '默认密码'%>
              </div>
              <% if judge.errors[:password].any? %>
                <dd class="error text-danger"><%= judge.errors[:password][0] %></dd>
              <% end %>
            </div>
            <div class="form-group">
              <div class="input-group input-padding" style="width: 100%;">
                <%= f.text_field :password_confirmation, class: 'form-control txt', placeholder: '默认密码'%>
              </div>
              <% if judge.errors[:password_confirmation].any? %>
                <dd class="error text-danger"><%= judge.errors[:password_confirmation][0] %></dd>
              <% end %>
            </div>
            <div class="text-center">
              <%= f.submit "提交", class: "btn sub-btn btn-primary", data: { disable_with: '正在提交...' } %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  function KeyP(v){
    document.getElementsById("txt").value = v.value;
  }
</script>

app/views/admin/judges/create.js.erb
<% if @judge.errors.present? %>
  $(".modal-backdrop").remove();
  $("#judgeModalContent").html("<%= escape_javascript( render "judges_modal", judge: @judge )%>");
  $('#judgeModal').modal('show');
<% else %>
  location.href = "<%= admin_judges_path %>"
<% end  %>

app/views/admin/judges/edit.js.erb
$("#judgeModalContent").html("<%= escape_javascript( render "judges_modal", judge: @judge )%>");
$('#judgeModal').modal('show')
$(".modal-header").click();

app/views/admin/judges/index.html.erb
<div id="wrapper">
  <%= render 'admin/share/left_nav'%>
  <div id="page-wrapper" class="gray-bg">
    <%= render 'admin/share/header'%>
    <div class="wrapper wrapper-content">
      <div class="lg-box animated fadeInRightBig">
        <div class="row">
          <div class="col-lg-12">
            <div class="ibox float-e-margins">
              <div class="ibox-title">
                <h5>评委信息表</h5>
                <div class="pull-right">
                  <%= link_to new_admin_judge_path, remote: true, format: :js, class: "ibox-title-new member-new" do %>
                    <i class="fa fa-plus fa-lg"></i>添加评委
                  <% end %>
                </div>
              </div>
              <div class="ibox-content">
                <table class="table">
                  <thead>
                    <tr class="text-center">
                      <th>序号</th>
                      <th>姓名</th>
                      <th>学院／学校</th>
                      <th>手机</th>
                      <th>编辑</th>
                    </tr>
                  </thead>
                  <tbody>
                  <% @judges.each_with_index do |judge, index| %>
                    <tr>
                      <td><%= index + 1 %></td>
                      <td><%= judge.email %></td>
                      <td>Otto</td>
                      <td>@mdo</td>
                      <td>
                        <%= link_to edit_admin_judge_path(id: judge.id), class: 'btn btn-xs btn-default', remote: true, format: :js do %>
                          <span class="glyphicon glyphicon-edit"></span>
                        <% end %>
                        <%= link_to admin_judge_path, method: :delete, class: 'btn btn-xs btn-danger' do %>
                          <span class="glyphicon glyphicon-trash"></span>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                  </tbody>
                  <tfoot>
                    <tr>
                      <td class="text-center" colspan="6">
                        <ul class="pagination"></ul>
                      </td>
                    </tr>
                  </tfoot>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <%= render 'admin/share/footer'%>
  </div>
</div>
<div id="judgeModalContent"></div>

app/views/admin/judges/new.html.erb
<h1>New Judge</h1>

<%= render 'form' %>

<%= link_to 'Back', judges_path %>

app/views/admin/judges/new.js.erb
$(".modal-backdrop").remove();
$("#judgeModalContent").html("<%= escape_javascript( render "judges_modal", judge: @judge  )%>");
$('#judgeModal').modal('show');

app/views/admin/judges/update.js.erb
<% if @judge.errors.present? %>
  $(".modal-backdrop").remove();
  $("#judgeModalContent").html("<%= escape_javascript( render "judges_modal", judge: @judge )%>");
  $('#judgeModal').modal('show');
<% else %>
  location.href = "<%= admin_judges_path %>"
<% end  %>